### ISSUE TITLE
TODO: Fix P-NP

### ISSUE THREAD

**Issue by afkvido** [ProdigyPNP/P-NP#1]

**Comment by donaldli2020** [comment]
assign me!

**Comment by donaldli2020** [comment]
for some reason i can't assign myself

**Comment by afkvido** [comment]
done :)

**Comment by Erisfiregamer1** [comment]
Fixed, check #2

**Comment by Erisfiregamer1** [comment]
Done. Unpinned and closed (because P-NP functions again).
Thank @donaldli2020  for their efforts in getting it working again.
