### ISSUE TITLE
P-NP Server

### ISSUE THREAD

**Issue by ProdigyPNPEnthusiast** [ProdigyPNP/P-NP#23]
I was just trying to use the hack and strangely ``_.instance`` was undefined. Then I saw the P-NP server was not synced with the base. Maybe syncing it would fix the error?

**Comment by afkvido** [comment]
I'm done with the obfuscated code. Time to open source it.

**Comment by afkvido** [comment]
It's all fixed :)

Also it wasn't just _.instance it was the entire lodash that broke

**Comment by ProdigyPNPEnthusiast** [comment]
Thanks for letting me know :)
